let items = [
  {
    objectId: "HiM6qZOmIJ",
    Model: "_Galaxy Tab Pro 12.1",
    Brand: "Samsung",
    img: "https://m.media-amazon.com/images/I/81vGY-eDAIL.jpg",
    price: 45555,
    Operating_System: "Android 4.4.2 (KitKat)| upgradable to 5.1.1 (Lollipop)",
    Internal_memory: "32/64 GB",
    RAM: "3 GB RAM",
    Primary_camera: "8 MP| autofocus| LED flash",
    Secondary_camera: "2 MP| 1080p@30fps",
    Battery: "Non-removable Li-Po 9500 mAh battery",
    createdAt: "2020-01-30T14:36:36.063Z",
    updatedAt: "2020-01-30T14:36:36.063Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "FKO1CYsFjM",
    Model: "_Galaxy Tab Pro 12.2 3G",
    Brand: "Samsung",
    img: "https://m.media-amazon.com/images/I/81vGY-eDAIL.jpg",
    price: 45555,
    Operating_System: "Android 4.4 (KitKat)",
    Internal_memory: "32/64 GB",
    RAM: "3 GB RAM",
    Primary_camera: "8 MP| autofocus| LED flash",
    Secondary_camera: "2 MP| 1080p@30fps",
    Battery: "Non-removable Li-Ion 9500 mAh battery",
    createdAt: "2020-01-30T14:36:36.063Z",
    updatedAt: "2020-01-30T14:36:36.063Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "LKFWF3xGmA",
    Model: "_iPhone 7 Plus",
    Brand: "Apple",
    img: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-7-plus-r2.jpg",
    price: 49900,
    Operating_System: "iOS 10.0.1| upgradable to iOS 10.3.2",
    Internal_memory: "32/128/256 GB",
    RAM: "3 GB RAM",
    Primary_camera: "Dual 12 MP| (28mm| f/1.8| OIS & 56mm| f/2.8)",
    Secondary_camera: "7 MP| f/2.2| 32mm| 1080p@30fps| 720p@240fps",
    Battery: "Non-removable Li-Ion 2900 mAh battery (11.1 Wh)",
    createdAt: "2020-01-30T14:36:36.382Z",
    updatedAt: "2020-01-30T14:36:36.382Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "KYLDqT18vC",
    Model: "_iPhone",
    Brand: "Apple",
    img: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-4-ofic-final.jpg",
    price: 10000,
    Operating_System: "iOS| upgradable to iOS 3.1.3",
    Internal_memory: "4/8/16 GB",
    Primary_camera: "2 MP",
    Secondary_camera: "No",
    Battery: "Non-removable Li-Ion battery",
    createdAt: "2020-01-30T14:36:36.339Z",
    updatedAt: "2020-01-30T14:36:36.339Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "fCBoRYbfkL",
    Model: "_iPhone 4",
    Brand: "Apple",
    img: "https://www.digitaltrends.com/wp-content/uploads/2010/06/apple-iphone-4-91.jpg?resize=650,450&p=1",
    price: 13999,
    Operating_System: "iOS 4| upgradable to iOS 7.1.2",
    Internal_memory: "8/16/32 GB",
    RAM: "512 MB RAM",
    Primary_camera: "5 MP| f/2.8| autofocus| LED flash|",
    Secondary_camera: "VGA| 480p@30fps| videocalling over Wi-Fi only",
    Battery: "Non-removable Li-Po 1420 mAh battery",
    createdAt: "2020-01-30T14:36:36.339Z",
    updatedAt: "2020-01-30T14:36:36.339Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "vUtG5HBhXH",
    Model: "_Honor 6 Plus",
    img: "https://m.media-amazon.com/images/I/61TgcgedlTL.jpg",
    price: 26499,
    Brand: "Huawei",
    Operating_System:
      "Android 4.4.2 (KitKat)| planned upgrade to 6.0 (Marshmallow)",
    Internal_memory: "16GB (3G model); 16/32 GB (LTE model)",
    RAM: "3 GB RAM",
    Primary_camera: "Dual 8 MP| f/2.0| autofocus| dual-LED flash",
    Secondary_camera: "8 MP| f/2.4| 1080p@30fps",
    Battery: "Non-removable Li-Po 3600 mAh battery",
    createdAt: "2020-01-30T14:36:36.252Z",
    updatedAt: "2020-01-30T14:36:36.252Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "WmBortPJMk",
    Model: "_Honor 7",
    img: "https://m-cdn.phonearena.com/images/phones/53916-350/Honor-7.jpg",
    price: 22999,
    Brand: "Huawei",
    Operating_System: "Android 5.0 (Lollipop)| upgradable to 6.0 (Marshmallow)",
    Internal_memory: "16/64 GB",
    RAM: "3 GB RAM",
    Primary_camera:
      "20 MP| f/2.0| 27mm| phase detection autofocus| dual-LED (dual tone) flash|",
    Secondary_camera: "8 MP| f/2.4| 26mm| LED flash",
    Battery: "Non-removable Li-Po 3100 mAh battery",
    createdAt: "2020-01-30T14:36:36.252Z",
    updatedAt: "2020-01-30T14:36:36.252Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "LKFWF3xGmA",
    Model: "_iPhone 7 Plus",
    Brand: "Apple",
    img: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-7-plus-r2.jpg",
    price: 12299,
    Operating_System: "iOS 10.0.1| upgradable to iOS 10.3.2",
    Internal_memory: "32/128/256 GB",
    RAM: "3 GB RAM",
    Primary_camera:
      "Dual 12 MP| (28mm| f/1.8| OIS & 56mm| f/2.8)| phase detection autofocus| 2x optical zoom| quad-LED (dual tone) flash|",
    Secondary_camera:
      "7 MP| f/2.2| 32mm| 1080p@30fps| 720p@240fps| face detection| HDR| panorama",
    Battery: "Non-removable Li-Ion 2900 mAh battery (11.1 Wh)",
    createdAt: "2020-01-30T14:36:36.382Z",
    updatedAt: "2020-01-30T14:36:36.382Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "LuDbvFh3iB",
    Model: "_KEYone",
    Brand: "BlackBerry",
    img: "https://fdn2.gsmarena.com/vv/bigpic/blackberry-keyone-mercury.jpg",
    price: 42990,
    Operating_System: "Android 7.1 (Nougat)",
    Internal_memory: "32 GB",
    RAM: "3 GB RAM",
    Primary_camera:
      "12 MP| f/2.0| phase detection autofocus| dual-LED (dual tone) flash",
    Secondary_camera: "8 MP| f/2.2| 1.12 �m pixel size| 1080p",
    Battery: "Non-removable Li-Ion 3505 mAh battery",
    createdAt: "2020-01-30T14:36:36.432Z",
    updatedAt: "2020-01-30T14:36:36.432Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "Ou4SaDtMZB",
    Model: "_Liquid Jade 2",
    Brand: "Acer",
    img: "https://cdn1.smartprix.com/rx-i1ytGKxqo-w500-h500/acer-liquid-jade-2.jpg",
    price: 6999,
    Operating_System: "Android 6.0 (Marshmallow)",
    Internal_memory: "32 GB",
    RAM: "3 GB RAM",
    Primary_camera: "21 MP| autofocus| dual-LED flash",
    Secondary_camera: "8 MP",
    createdAt: "2020-01-30T14:36:36.566Z",
    updatedAt: "2020-01-30T14:36:36.566Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "vxGV9TaOQo",
    Model: "_Liquid Jade Primo",
    Brand: "Acer",
    img: "https://fdn2.gsmarena.com/vv/bigpic/acer-liquid-jade-primo-.jpg",
    price: 7999,
    Operating_System: "Microsoft Windows 10",
    Internal_memory: "32 GB",
    RAM: "3 GB RAM",
    Primary_camera: "21 MP| f/2.2| autofocus| dual-LED flash|",
    Secondary_camera: "8 MP| f/2.2| 1080p@30fps",
    Battery: "Non-removable Li-Po 2870 mAh battery",
    createdAt: "2020-01-30T14:36:36.566Z",
    updatedAt: "2020-01-30T14:36:36.566Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "h1DAThQvKH",
    Model: "_Liquid Z630S",
    Brand: "Acer",
    img: "https://m-cdn.phonearena.com/images/phones/55078-350/Acer-Liquid-Z630S.jpg",
    price: 8999,
    Operating_System: "Android 5.1 (Lollipop)",
    Internal_memory: "32 GB",
    RAM: "3 GB RAM",
    Primary_camera: "8 MP| autofocus| LED flash",
    Secondary_camera: "8 MP",
    Battery: "Removable Li-Po 4000 mAh battery (15.2 Wh)",
    createdAt: "2020-01-30T14:36:36.566Z",
    updatedAt: "2020-01-30T14:36:36.566Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "B1NDYdZ9yj",
    Model: "_Liquid X2",
    Brand: "Acer",
    img: "https://m.media-amazon.com/images/I/71hj5uzguWL.jpg",
    price: 7990,
    Operating_System: "Android 5.1 (Lollipop)",
    Internal_memory: "32 GB",
    RAM: "3 GB RAM",
    Primary_camera: "13 MP| f/1.8| autofocus| LED flash|",
    Secondary_camera: "13 MP| f/1.8| autofocus| LED flash",
    Battery: "Removable Li-Po 4020 mAh battery",
    createdAt: "2020-01-30T14:36:36.566Z",
    updatedAt: "2020-01-30T14:36:36.566Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "N7QOPmNqoE",
    Model: "_Mi 4s",
    Brand: "Xiaomi",
    img: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi-4s.jpg",
    price: 6999,
    Operating_System: "Android 5.1 (Lollipop)",
    Internal_memory: "64 GB",
    RAM: "3 GB RAM",
    Primary_camera:
      "13 MP| f/2.0| phase detection autofocus| dual-LED (dual tone) flash|",
    Secondary_camera: "5 MP| f/2.0| 1080p",
    Battery: "Non-removable Li-Ion 3260 mAh battery",
    createdAt: "2020-01-30T14:36:36.751Z",
    updatedAt: "2020-01-30T14:36:36.751Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "2UeKbVo6f6",
    Model: "_V5s",
    Brand: "vivo",
    img: "https://fdn2.gsmarena.com/vv/bigpic/vivo-v5s.jpg",
    price: 5899,
    Operating_System: "Android 6.0 (Marshmallow)",
    Internal_memory: "64 GB",
    RAM: "4 GB RAM",
    Primary_camera: "13 MP| F/2.2| phase detection autofocus| LED flash",
    Secondary_camera: '20 MP| f/2.0| 1/2.8" sensor size| 1080p',
    Battery: "Non-removable Li-Ion 3000 mAh battery",
    createdAt: "2020-01-30T14:36:38.112Z",
    updatedAt: "2020-01-30T14:36:38.112Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "wnWiYRa2O9",
    Model: "_Vibe Z3 Pro",
    Brand: "Lenovo",
    img: "https://fdn2.gsmarena.com/vv/bigpic/smartphone.jpg",
    price: 7650,
    Operating_System: "Android 5.0.2 (Lollipop)",
    Internal_memory: "32 GB",
    RAM: "4 GB RAM",
    Primary_camera: "16 MP| OIS| laser autofocus| dual-LED flash",
    Secondary_camera: "8 MP",
    Battery: "Non-removable Li-Po 3400 mAh battery",
    createdAt: "2020-01-30T14:36:38.158Z",
    updatedAt: "2020-01-30T14:36:38.158Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "tsSSkq7Asj",
    Model: "_X6",
    Brand: "vivo",
    img: "https://www.droidafrica.net/wp-content/uploads/2021/10/BLU-Vivo-X6-droidafrica-1-600x600.jpg",
    price: 6652,
    Operating_System: "Android 5.1 (Lollipop)",
    Internal_memory: "32 GB",
    RAM: "4 GB RAM",
    Primary_camera: "13 MP| f/2.2| phase detection autofocus| LED flash",
    Secondary_camera: "8 MP| f/2.4",
    Battery: "Non-removable Li-Ion 2400 mAh battery",
    createdAt: "2020-01-30T14:36:38.352Z",
    updatedAt: "2020-01-30T14:36:38.352Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "hk9YM1C7EM",
    Model: "_X7",
    Brand: "vivo",
    img: "https://fdn2.gsmarena.com/vv/bigpic/vivo-x7.jpg",
    price: 9999,
    Operating_System: "Android 5.1 (Lollipop)",
    Internal_memory: "64 GB",
    RAM: "4 GB RAM",
    Primary_camera: "13 MP| f/2.2| phase detection autofocus| LED flash",
    Secondary_camera: "16 MP| f/2.0| LED flash",
    Battery: "Non-removable Li-Ion 3000 mAh battery",
    createdAt: "2020-01-30T14:36:38.401Z",
    updatedAt: "2020-01-30T14:36:38.401Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "jMUXD1D3C5",
    Model: "_Xperia XZ Premium",
    Brand: "Sony",
    img: "https://m.media-amazon.com/images/I/71LZgCGSz2L.jpg",
    price: 12099,
    Operating_System: "Android 7.1 (Nougat)",
    Internal_memory: "64 GB",
    RAM: "4 GB RAM",
    Primary_camera:
      "19 MP| f/2.0| 25mm| EIS (gyro)| predictive phase detection and laser autofocus| LED flash|",
    Secondary_camera:
      '13 MP| f/2.0| 22mm| 1/3" sensor size| 1.12 �m pixel size| 1080p',
    Battery: "Non-removable Li-Ion 3230 mAh battery",
    createdAt: "2020-01-30T14:36:38.502Z",
    updatedAt: "2020-01-30T14:36:38.502Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "pVTzKKHKs8",
    Model: "_Zenfone 2 Deluxe ZE551ML",
    Brand: "Asus",
    img: "https://fdn2.gsmarena.com/vv/bigpic/asus-zenfone-2-new.jpg",
    price: 5999,
    Operating_System:
      "Android 5.0 (Lollipop)| planned upgrade to 6.0 (Marshmallow)",
    Internal_memory: "64/128 GB",
    RAM: "4 GB RAM",
    Primary_camera: "13 MP| f/2.0| autofocus| dual-LED (dual tone) flash",
    Secondary_camera: "5 MP| f/2.0",
    Battery: "Non-removable Li-Po 3000 mAh battery",
    createdAt: "2020-01-30T14:36:38.605Z",
    updatedAt: "2020-01-30T14:36:38.605Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "iK6UVGOV4t",
    Model: "_10",
    Brand: "HTC",
    img: "https://fdn2.gsmarena.com/vv/bigpic/htc-10-r.jpg",
    price: 47990,
    Operating_System: "Android 6.0.1 (Marshmallow)| upgradable to 7.0 (Nougat)",
    Internal_memory: "32/64 GB",
    RAM: "4 GB RAM",
    Primary_camera:
      "12 MP| f/1.8| 26mm| OIS| laser autofocus| dual-LED (dual tone) flash|",
    Secondary_camera:
      "5 MP| f/1.8| 23mm| OIS| autofocus| 1.34 �m pixel size| 1080p| HDR",
    Battery: "Non-removable Li-Ion 3000 mAh battery",
    createdAt: "2020-01-30T14:36:33.639Z",
    updatedAt: "2020-01-30T14:36:33.639Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "G7mNk6H9Lx",
    Model: "_F1 Plus",
    Brand: "Oppo",
    img: "https://fdn2.gsmarena.com/vv/bigpic/oppo-f1s.jpg",
    price: 5099,
    Operating_System: "Android 5.1 (Lollipop)",
    Internal_memory: "64 GB",
    RAM: "4 GB RAM",
    Primary_camera: "13 MP| f/2.2| phase detection autofocus| LED flash|",
    Secondary_camera: "16 MP| f/2.0",
    Battery: "Non-removable Li-Po 2850 mAh battery",
    createdAt: "2020-01-30T14:36:35.776Z",
    updatedAt: "2020-01-30T14:36:35.776Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "M49rUBEYbH",
    Model: "_F3",
    Brand: "Oppo",
    img: "https://fdn2.gsmarena.com/vv/bigpic/oppo-f3-plus.jpg",
    price: 20990,
    Operating_System: "Android 6.0 (Marshmallow)",
    Internal_memory: "64 GB",
    RAM: "4 GB RAM",
    Primary_camera: "13 MP| f/2.2| phase detection autofocus| LED flash|",
    Secondary_camera: 'Dual 16 MP (1/3.1" sensor size| f/2.0) + 8 MP| f/2.4',
    Battery: "Non-removable Li-Ion 3200 mAh battery",
    createdAt: "2020-01-30T14:36:35.776Z",
    updatedAt: "2020-01-30T14:36:35.776Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "6wGSaWrISR",
    Model: "_G4 Pro",
    Brand: "LG",
    img: "https://fdn2.gsmarena.com/vv/bigpic/lg-g4-.jpg",
    price: 41500,
    Operating_System: "Android 5.1 (Lollipop)",
    Internal_memory: "32/64 GB",
    RAM: "4 GB RAM",
    Primary_camera: "27 MP| laser autofocus| OIS| LED flash",
    Secondary_camera: "8 MP| 1080p@30fps",
    Battery: "Removable Li-Ion battery",
    createdAt: "2020-01-30T14:36:35.870Z",
    updatedAt: "2020-01-30T14:36:35.870Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
  {
    objectId: "CRAAwVGvOc",
    Model: "_iPhone SE",
    Brand: "Apple",
    img: "https://m.media-amazon.com/images/I/31rSERJARAL.jpg",
    price: 43900,
    Operating_System: "iOS 9.3.2| upgradable to iOS 10.3.2",
    Internal_memory: "16/32/64/128 GB",
    RAM: "2 GB RAM",
    Primary_camera:
      "12 MP| f/2.2| 29mm| phase detection autofocus| dual-LED (dual tone) flash|",
    Secondary_camera:
      "1.2 MP| f/2.4| 31mm| 720p@30fps| face detection| HDR| FaceTime over Wi-Fi or Cellular",
    Battery: "Non-removable Li-Po 1624 mAh battery (6.21 Wh)",
    createdAt: "2020-01-30T14:36:36.382Z",
    updatedAt: "2020-01-30T14:36:36.382Z",
    Cell_Phone_Brands: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
    Cell_Phone_Models: {
      __type: "Relation",
      className: "Cellphonedataset_Dataset_Cell_Phones_Model_Brand",
    },
  },
];
export default items;
